"""Culprit evidence test gating for INC-001.

Generated by `culprit open INC-001`. Do not edit by hand.
"""
import os
from pathlib import Path

import pytest


def pytest_collection_modifyitems(items, config):
    """Skip tests for cleared or inconclusive suspects unless CULPRIT_RUN_EVIDENCE=1."""
    if os.environ.get("CULPRIT_RUN_EVIDENCE") == "1":
        return

    ledger_path = Path(".culprit/INC-001/ledger.json")
    if not ledger_path.exists():
        return

    import json
    try:
        ledger = json.loads(ledger_path.read_text(encoding="utf-8"))
    except Exception:
        return

    suspect_status = {s["id"]: s["status"] for s in ledger.get("suspects", [])}

    # Map test_ids to suspect_ids from ledger
    test_to_suspect = {}
    for s in ledger.get("suspects", []):
        for t_id in s.get("test_ids", []):
            test_to_suspect[t_id] = s["id"]

    for item in items:
        # Read the module docstring to find suspect id
        module = item.module if hasattr(item, "module") else None
        doc = module.__doc__ if module else ""
        suspect_id = None
        if doc:
            for line in doc.splitlines():
                line = line.strip()
                if line.startswith("suspect:"):
                    suspect_id = line.split(":", 1)[1].strip()
                    break

        if suspect_id:
            status = suspect_status.get(suspect_id, "suspect")
            if status in ("cleared", "inconclusive"):
                # Find test_id for this suspect from ledger
                test_ids = next(
                    (s.get("test_ids", []) for s in ledger.get("suspects", []) if s["id"] == suspect_id),
                    []
                )
                ledger_ref = test_ids[0] if test_ids else suspect_id
                item.add_marker(pytest.mark.skip(
                    reason=f"Culprit evidence for a cleared suspect, see ledger {ledger_ref}"
                ))
